### PR TITLE
PatternLab

### PR DESCRIPTION
**Pull request by valguss**
- Added in patternlab building support
- Updated readme with extra configuration options

### CODE REVIEW

**Comment by Demoli** [comment]
See this for gulp config https://github.com/Skywire/corneyandbarrow.com/blob/capistrano/tools/cap/config/deploy.rb

**Comment by valguss** [comment]
New pattern lab is using `npm run pl:build` rather than gulp

**Comment by Demoli** [comment]
We'll need a generic way of handling NPM then, the intention is to merge some of this stuff back into the original repository, so we can't have skywire specific code in there.

**Comment by valguss** [comment]
Hmmmm. Will have a think about how to do that

**Comment by valguss** [comment]
Have a gander at that then.

**Comment by valguss** [comment]
q removed

**Comment by Demoli** [comment]
Looks good, happy for that to be merged.

**Pull request merged**
